### ISSUE TITLE
ObsPy error: Tried installing ObsPyck with miniconda3 

### ISSUE THREAD

**Issue by aileen-fisher** [megies/obspyck#108]
(base) bash-4.2$ conda activate obspyck                                                                           
(obspyck) bash-4.2$ obspyck -h                                                                                    
Traceback (most recent call last):                                                                                
  File "/data/studies/ObsPyck/miniconda3/envs/obspyck/bin/obspyck", line 6, in <module>                           
    from obspyck.obspyck import main                                                                              
  File "/data/studies/ObsPyck/miniconda3/envs/obspyck/lib/python3.11/site-packages/obspyck/obspyck.py", line 54, in <module>                                                                                                        
    from .qt_designer import Ui_qMainWindow_obsPyck                                                               
  File "/data/studies/ObsPyck/miniconda3/envs/obspyck/lib/python3.11/site-packages/obspyck/qt_designer.py", line 958, in <module>                                                                                                   
    from .util import QMplCanvas
  File "/data/studies/ObsPyck/miniconda3/envs/obspyck/lib/python3.11/site-packages/obspyck/util.py", line 33, in <module>
    import obspy.clients.arclink
ModuleNotFoundError: No module named 'obspy.clients.arclink'

**Comment by aileen-fisher** [comment]
From ObsPy Changelog (https://docs.obspy.org/changelog.html):

obspy.clients.arclink:

    submodule removed completely, since ArcLink was officially deprecated and deactivated on all big datacenters years ago (see #2994)

**Comment by megies** [comment]
you either need an older obspy version <1.3 or you can remove your obspyck package and then install master branch like..

```
conda remove --force --offline obspyck
pip install https://github.com/megies/obspyck/archive/refs/heads/master.zip
```
