### ISSUE TITLE
How to use nonlinloc with obspyck?

### ISSUE THREAD

**Issue by megies** [megies/obspyck#11]
```
Thanks, but now when running with NLloc there's an error message
(below). It may be related to NLloc's control and model files, but
it's not clear how these need to be setup for obspyck. Any
suggestions?


Traceback (most recent call last):
  File "./obspyck.py", line 433, in on_qToolButton_doNlloc_clicked
    self.doNLLoc()
  File "./obspyck.py", line 1910, in doNLLoc
    files = prog_dict['files']
KeyError: 'files'
```

try the following:
- in your obspyck folder make a subdirectory "nlloc"
- put your nonlinloc control file in that folder, naming it
  "locate_BY.nlloc"
- put your nonlinloc travel time cubes (the *.hdr and *.buf files you
  generated with nonlinloc from your velocity models) in a subfolder
  of "nlloc" folder
- make sure that in the control file the "LOCFILES" line looks like
  the following:

`LOCFILES ./nlloc.obs NLLOC_OBS ./AAA/BBB ./nlloc`
- replace "AAA" with the name of the subfolder with the travel time
  cubes
- replace "BBB" with the prefix of the travel time cube files
  (e.g. put "VERSION3" for cubes named like e.g.
  "VERSION3.P.UH1.time.buf", for a P travel time cube for station UH1)
- start obspyck with option --pluginpath='/my/obspyck/folder' pointing
  it to the folder where your obspyck.py is with the "nlloc" subfolder.

```
Thanks for posting instructions on how to setup Obspyck with NLloc.
But ran into another issue. By default Obspyck seems to be looking
first for Hypo2000. Error message below.

Warning: SeisHub specific features will not work (e.g. 'send Event').
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/obspy/fdsn/wadl_parser.py:106:
UserWarning: The 'event' service at
'http://www.seismicportal.eu/fdsnws/event/1/' cannot deal with the following
required parameters: magnitudetype
They will not be available for any requests. Any attempt to use them will result
in an error.
  warnings.warn(msg)
Could not determine possible arrivals using obspy.fdsn/taup.
Problem while fetching events or determining theoretical phases: KeyError:
'coordinates'
Traceback (most recent call last):
  File "./obspyck.py", line 4015, in <module>
    main()
  File "./obspyck.py", line 4009, in main
    obspyck = ObsPyck(clients, streams, options, KEYS)
  File "./obspyck.py", line 200, in __init__
    self.tmp_dir = setup_external_programs(options)
  File "~/test/obspyck/obspyck/util.py", line 664, in setup_external_programs
    shutil.copytree(prog_srcpath, prog_tmpdir, symlinks=True)
  File
"/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py",
line 171, in copytree
    names = os.listdir(src)

OSError: [Errno 2] No such file or directory: '~/test/obspyck/obspyck/hyp_2000'
```

Please simply create empty `hyp_2000` and `focmec` directories in your designated obspyck pluginpath directory.

**Comment by AntonBiryukov** [comment]
Hi Tobias,

I am sorry for any inconvenience I might cause, but I 'd like to wonder about one more thing.

Is there an option to pass the existing NonLinLoc solution from a local file to the Obspyck for the corresponding event (similar to passing the event information as --event myevent.xml), so that the takeoff angles, phases and azimuths are somehow parsed to be passed to FocMec ?

Best regards,

Anton.

**Comment by megies** [comment]
Sorry, that's some really strange use case.. You are using obspyck to pick data, then do nonlinloc externally and then want to load the event into obspyck to run focmec??

I would say either do nonlinloc also from inside obspyck or just do focmec with the output data of obspyck?

Note that obspy can read nonlinloc output into a catalog object. http://docs.obspy.org/packages/obspy.nlloc.html?highlight=nlloc#obspy.nlloc

**Comment by AntonBiryukov** [comment]
Hey Tobias,

The use-case is a bit different, as picks were picked by some other in-house software. Using obspy, I have managed to convert the picks from nlloc files into QuakeML. However, nonlinloc omits the information about the channel and location / network codes, so they can't be easily visualized in the obspyck, as ObsPyck does not know which channel assign the picks on.

Eventually, I 'll end up using focmec separately, but it would be good to have the pick visualization in the obspyck from the external nonlinloc file / converted QuakeML.

**Comment by megies** [comment]
Well, if you parse some nonlinloc output file and write to QuakeML why not insert the correct network/location codes (you should know them I suppose). If you don't know the channel, why not just insert the channels you want to llok at (e.g. Z for P and N for S)?
Anyway, that really hardly sounds like an ObsPyck problem.

**Comment by klaaur** [comment]
I'm having a similar error as AbeJones except that I can't seem to get my 'Missing pick error message' to go away:

/var/folders/z6/2x3y1cqs6xd75sx8ztzsfdnm002t75/T/obspyck-FV1Kt4/nlloc/nlloc*
Warning: Missing pick error. Using a default error of 0.05s for P phase of station BBR. Please set pick errors.
Warning: Missing pick error. Using a default error of 0.05s for P phase of station BBR. Please set pick errors.
Warning: Missing pick error. Using a default error of 0.05s for P phase of station BBR. Please set pick errors.
Phases for NLLoc:
BBR    ?    ?    ? P      ? 20110311 0558 36.5195 GAU  5.00e-02 -1.00e+00 -1.00e+00 -1.00e+00
BBR    ?    ?    ? P      ? 20110311 0558 36.5195 GAU  5.00e-02 -1.00e+00 -1.00e+00 -1.00e+00
BBR    ?    ?    ? P      ? 20110311 0558 45.5695 GAU  5.00e-02 -1.00e+00 -1.00e+00 -1.00e+00

Traceback (most recent call last):
  File "obspyck.py", line 442, in on_qToolButton_doNlloc_clicked
    self.doNLLoc()
  File "obspyck.py", line 2071, in doNLLoc
    (msg, err, returncode) = call(prog_dict, controlfilename)
  File "/Users/kaaur/Downloads/obspyck-develop/util.py", line 853, in tmp
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "//anaconda/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "//anaconda/lib/python2.7/subprocess.py", line 1323, in _execute_child
    data = _eintr_retry_call(os.read, errpipe_read, 1048576)
  File "//anaconda/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
OSError: [Errno 22] Invalid argument

I've set pick errors (e.g., I+1) in the GUI window then press do_NLLoc with the BY option selected. Note I'm on a mac. I have not investigated the subprocess issue yet that you mentioned above. I have my setup as you described at the top of this thread. Note that I'm using the example global config file from nlloc_global_sample (neic_global.in) with the taup/ak135 HDR and buf files and without including the sta_list_neic.in file in the config file. Do you have an example config file that works with the EXAMPLE 1 stations? I figured the default global config file should work with just about any station. I have never used nlloc so there may be obvious things I'm overlooking. Do you know what the issue might be? Thanks!

**Comment by klaaur** [comment]
Note I was able to make the missing pick error messages go away by adding error bars to the picks with a right click. I'm still having issues with the IOError: [Errno 2] creating the nlloc.hyp file.

**Comment by klaaur** [comment]
Using the verbose mode in the config file I get the following:

./NLLoc__Darwin__64bit locate_BY.nlloc 
NLLoc (NonLinLoc v6.00.0 18Mar2011) 
GRID: {x, y, z}
  Num: {361, 181, 601}
  Orig: {-180, -90, 0}
  LenSide: {1, 1, 1}
  Type: PROB_DENSITY
LOCGAUSS2:  SigmaTfraction: 0.010000  SigmaTmin: 0.050000  SigmaTmax: 2.000000
NLLoc LOCQUAL2ERR:
 0 ->  0.200000
 1 ->  0.500000
 2 ->  1.000000
 3 ->  2.000000
 4 ->  99999.900000
INFO: no phase identifier (LOCPHASEID) values read.
INFO: no station distance weighting (LOCSTAWT) values read.
INFO: no Magnitude Calculation (LOCMAG) params read.
INFO: no Component Descirption (LOCCMP) params read.
INFO: no Alias (LOCALIAS) params read.
INFO: no Exclude (LOCEXCLUDE) params read.
INFO: no Time Delay (LOCDELAY) params read.
INFO: no Topo Surface (LOCTOPO_SURFACE) params read.
INFO: no Time Delay Surface (LOCDELAY_SURFACE) params read.
INFO: no Elevation Correction (LOCELEVCORR) params read.
INFO: no Fixed Origin Time (LOCFIXOTIME) params read.

... Reading observation file ./nlloc.obs

Reading next set of observations (Files open: Tot:2 Buf:0 Hdr:0  Alloc: 0) ...

... 4 observations read, 4 will be used for location (./nlloc.20110311.055446).
LOCGAU param CorrLen is zero, will not be used: 0.000000
Locating... (Files open: Tot:2 Buf:0 Hdr:0  Alloc: 4  3DMem: 0) ...

Applying Octtree search within Grid 0:
Station Density Weight:  Ave Station Distance: 9416.598382
Station Density Weight:  Mean Root Node Horiz dS: 833.333333
EDT_otime_weight activated, OT_WT exceeds EDT_OT_WT_FLOOR.
OctTree num samples = 50000 / 50000
Octree oct_node_value_max= -3.261204e+01 oct_tree_integral= 5.556205e+05
OCTREE nInitial 27648 nEvaluated 50008 smallestNodeSide 6.510417/6.510417/1.565104 oct_tree_integral 5.556205e+05
EDT_otime_weight: ot_ml_std 0.510669

Station Density Weight:  Number Force Divide: 27332  max_num_nodes: 50000
Segmentation fault: 11

I found however that the config file in my /tmp folder is not the one that I use to in my plugin_dir/nlloc directory?

**Comment by megies** [comment]
Looks like you're getting pretty far with nonlinloc, the segfault probably has to do with the values you used when compiling NonLinLoc..?

> I found however that the config file in my /tmp folder is not the one that I use to in my plugin_dir/nlloc directory?

The temporary directory should be a copy of your plugin_dir.. so it seems strange that some files are not the same..?

**Comment by klaaur** [comment]
@megies My current problem is getting nlloc to finish running with my locate_BY.nlloc file. I'm using the default neic_global.in file from the nlloc examples with the sta_list.neic.in file. I've selected a few stations to get picks from that are included in the station list file, I select the P-picks and the error bars, then click on the doNLLoc button and obtain the following error:

Warning: SeisHub specific features will not work (e.g. 'send Event').
/var/folders/z6/2x3y1cqs6xd75sx8ztzsfdnm002t75/T/obspyck-TEJra4/nlloc/nlloc*
Phases for NLLoc:
AAK    ?    ?    ? P      ? 20110311 0555 28.1695 GAU  2.65e+02 -1.00e+00 -1.00e+00 -1.00e+00
ARU    ?    ?    ? P      ? 20110311 0556  4.1284 GAU  1.30e+02 -1.00e+00 -1.00e+00 -1.00e+00
KURK   ?    ?    ? P      ? 20110311 0554 43.2308 GAU  1.48e+02 -1.00e+00 -1.00e+00 -1.00e+00
RPN    ?    ?    ? P      ? 20110311 0606 37.6699 GAU  2.34e+02 -1.00e+00 -1.00e+00 -1.00e+00

<subprocess.Popen object at 0x124065610>

--> NLLoc finished
Traceback (most recent call last):
  File "obspyck.py", line 442, in on_qToolButton_doNlloc_clicked
    self.doNLLoc()
  File "obspyck.py", line 2075, in doNLLoc
    self.catFile(files['summary'], self.critical)
  File "obspyck.py", line 2078, in catFile
    lines = open(file, "rt").readlines()
IOError: [Errno 2] No such file or directory: '/var/folders/z6/2x3y1cqs6xd75sx8ztzsfdnm002t75/T/obspyck-TEJra4/nlloc/nlloc.hyp'

I get the first phase output and the NLLoc finished print out but I don't get any of the location information or the focmech solution. Do you have a configuration file that works with the EXAMPLE1 stations in the default ~/.obspyckrc file? Or another NLLOC config file that works with stations and events I could test out my configuration with and pull data from the FDSN server? I'm struggling to find out where my issue is? As I mentioned this is my first time using NLLOC so there could be something simple that I'm overlooking. For example, does the global NLLOC version require that I recalculate the AK135 travel grid. I have the default ak135 HDR and buf files from the samples. Or would I need to specify that somewhere in obspyck?

**Comment by klaaur** [comment]
Update: I have nlloc working now. I went back through the global sample run and retested it with the default files then re-ran in my /tmp directory. Once I got that working I was able to repair my link issue that was causing the wrong input file to be utilized. Now there's a map issue: 

--> NLLoc finished
NLLOC "./nlloc.20110311.055456.grid0" "LOCATED" "Location completed."
SIGNATURE "Anthony Lomax (www.alomax.net)   NLLoc:v6.00.0 20Oct2016 13h13m04"
COMMENT "NEIC events"
GRID  361 181 601  -180 -90 0  1 1 1 PROB_DENSITY
SEARCH OCTREE nInitial 27648 nEvaluated 50008 smallestNodeSide 208.333333/208.333333/50.083333 oct_tree_integral 6.517140e+14 scatter_volume 6.517140e+14
HYPOCENTER  x 72.1875 y 49.6875 z 475.792  OT 37.8976  ix -1 iy -1 iz -1
GEOGRAPHIC  OT 2011 03 11  05 53   37.8976  Lat 49.6875 Long 72.1875 Depth 475.792
QUALITY  Pmax 8.5938e-07 MFmin 1.87642 MFmax 1.94584 RMS 24.2215 Nphs 4 Gap 138.311 Dist 4.24555 Mamp  -9.9 0 Mdur  -9.9 0
VPVSRATIO  VpVsRatio -1  Npair 0  Diff -2e+30
STATISTICS  ExpectX -12.0572 Y 2.39559 Z 304.745  CovXX 1.4045e+08 XY 324123 XZ -368685 YY 2.06086e+07 YZ 2392.82 ZZ 29709.4 EllAz1  93.4352 Dip1  89.8493 Len1  318.521 Az2  359.845 Dip2  0.00943817 Len2  8529.08 Len3  2.226649e+04
STAT_GEOG  ExpectLat 2.39559 Long -12.0572 Depth 304.745
TRANSFORM  GLOBAL
QML_OriginQuality  assocPhCt 4  usedPhCt 4  assocStaCt -1  usedStaCt 4  depthPhCt -1  stdErr 24.2215  azGap 138.311  secAzGap 257.053  gtLevel -  minDist 471.728 maxDist 17503.1 medDist 989.697
QML_OriginUncertainty  horUnc -1  minHorUnc 6884.6  maxHorUnc 17973.3  azMaxHorUnc 89.845
FOCALMECH  Hyp  49.6875 72.1875 475.792 Mech  0 0 0 mf  0 nObs 0
PHASE ID Ins Cmp On Pha  FM Date     HrMn   Sec     Err  ErrMag    Coda      Amp       Per  >   TTpred    Res       Weight    StaLoc(X  Y         Z)        SDist    SAzim  RAz  RDip RQual    Tcorr 
KURK   ?    ?    ? P      ? 20110311 0554     56.73 GAU        72        -1        -1        -1 >   78.8333   -0.0000    1.2662   78.6202   50.7154   -0.1840    4.2455  73.53   0.0   0.0  0     0.0000
AAK    ?    ?    ? P      ? 20110311 0555     23.67 GAU        76        -1        -1        -1 >  107.7615   -1.9896    1.2544   74.4940   42.6390   -1.6450    7.2318 166.39   0.0   0.0  0     0.0000
ARU    ?    ?    ? P      ? 20110311 0556     4.128 GAU        99        -1        -1        -1 >  143.3728    2.8580    1.1648   58.5625   56.4302   -0.2500   10.5828 314.78   0.0   0.0  0     0.0000
RPN    ?    ?    ? P      ? 20110311 0607      4.62 GAU   5.8e+02        -1        -1        -1 > 1028.9717 -222.2494    0.3147 -109.3344  -27.1267   -0.1100  157.5276 176.47   0.0   0.0  0     0.0000
END_PHASE
END_NLLOC


no station magnitudes (or all deselected), nothing to do...
Traceback (most recent call last):
  File "./obspyck.py", line 477, in on_qToolButton_showMap_toggled
    self.drawEventMap()
  File "./obspyck.py", line 3045, in drawEventMap
    coords = st[0].stats.coordinates
  File "//anaconda/lib/python2.7/site-packages/obspy/core/util/attribdict.py", line 125, in __getattr__
    raise AttributeError(e.args[0])
AttributeError: coordinates

**Comment by megies** [comment]
Are you feeding waveforms via local files? Or via fetching from servers? Looks like metadata is missing..

**Comment by klaaur** [comment]
I'm fetching data from servers

**Comment by megies** [comment]
FDSN, I guess? Are there any error messages up until obspyck window pops up? Because, coordinates should be attached for FDSN servers correctly, see https://github.com/megies/obspyck/blob/master/util.py#L458-L474

**Comment by klaaur** [comment]
There aren't any errors to suggest the metadata wasn't being obtained. What I didn't realize was that the default obspyckrc has 'no_metadata' set to true. Updating this variable to false fixed the issue. Thanks.

**Comment by megies** [comment]
> default obspyckrc has 'no_metadata' set to true

Really? Are you sure? I think it should have it set to `false`... https://github.com/megies/obspyck/blob/master/example.cfg#L23

**Comment by klaaur** [comment]
I must've changed it while doing some other tests, but once I changed it back to false I was able to get the information necessary for the showMap feature. Thanks for your help in this. When you do get around to it it might help to have a working global example and a local example, if possible. Or an example that works with your EXAMPLE1 stations in the .obspyckrc file. I think it would help users immensely get everything up and running. Thanks again. I have a few other issues I'm running into that I'll post into other issue threads.

**Comment by klaaur** [comment]
After nlloc has finished running, the 'show Map' feature is toggled Could you explain what's being shown in the 3 small graphs in the top right corner? Thanks

**Comment by megies** [comment]
That's a view of the nonlinloc scatter file: http://alomax.free.fr/nlloc/soft6.00/formats.html#_location_scat_
