### ISSUE TITLE
Integrating with hypo_2000

### ISSUE THREAD

**Issue by shicks-seismo** [megies/obspyck#53]
Dear Tobias,

I'm having problems running hypo_2000 from Obspyck.

In the temporary working directory, I have the following files: bay2000.inp; gey.crh; hyp2000; hyp2000.pha; hypo.arc; hypo.sum; stations.dat (hopefully these are named correctly)

If I run hypo_2000 in standalone mode using these files, the location works correctly; however, with Obspyck, I get the following error:

> Traceback (most recent call last):
>   File "/Users/sph1r17/anaconda/envs/obspy_2.7/lib/python2.7/site-packages/obspyck-0.4.1.post0-py2.7.egg/obspyck/obspyck.py", line 446, in on_qToolButton_doHyp2000_clicked
>     self.doHyp2000()
>   File "/Users/sph1r17/anaconda/envs/obspy_2.7/lib/python2.7/site-packages/obspyck-0.4.1.post0-py2.7.egg/obspyck/obspyck.py", line 2114, in doHyp2000
>     call = prog_dict['Call']
>   File "/Users/sph1r17/anaconda/envs/obspy_2.7/lib/python2.7/site-packages/obspyck-0.4.1.post0-py2.7.egg/obspyck/util.py", line 858, in tmp
>     stdin=subprocess.PIPE,
>   File "/Users/sph1r17/anaconda/envs/obspy_2.7/lib/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/Users/sph1r17/anaconda/envs/obspy_2.7/lib/python2.7/subprocess.py", line 1343, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory

I am confused how Obspyck tells the shell to run hyp2000 and then provides the correct name of the command file within hyp2000.

Maybe it is working properly but the Mac problems described in this thread are occurring: [https://github.com/megies/obspyck/issues/11#issuecomment-59489271].

Nevertheless, it would be good to have your input.

**Comment by shicks-seismo** [comment]
Okay, as you can see from my Pull Requests, this issue is now sorted after staring at the code for a long time!

The problem was solved for my Mac by removing the 'shell=SHELL' argument to the subprocess command for HYPO2000 and NLLoc (Lines 855 and 897 of util.py).

I haven't formally requested a pull for this issue because I didn't know how such a change might affect Obspyck on Linux.

**Comment by shicks-seismo** [comment]
So my final (hopefully!) question regards the coordinate conversion from NLLoc output back to lat, long. I see in the code that you use the gk2lonlat to convert Gauss-Krueger coordinates to lat, long.

Could you please explain some more about this methodology.
Do I need to define my NLLoc velocity grid in a special way? 
Do I need to define the pyproj init value to the zone / central merdian that I am interested in?

Many thanks again.

**Comment by megies** [comment]
hey @shicks-seismo sorry for not being able to help much with above issue, the subprocess/wait/shell stuff has made some issues before, but since i'm not using MAC I can only rely on what people report back..

> coordinate conversion from NLLoc

this is all about what coordinates you use in nonlinloc. I assume you dont use `global` mode but some local coordinates, so you need to replace `gk2lonlat` with whatever coordinate conversion you need from your nonlinloc reference system to WGS. What coordinates do you use in nonlinloc?

**Comment by echavess** [comment]
Ok. Nevermind. I solved it installing the new version of NLLOC which brings support for mac osx.

**Comment by megies** [comment]
> Ok. Nevermind. I solved it installing the new version of NLLOC which brings support for mac osx.

Old versions used to work on Mac, too. But I never compiled it myself. Anyway, glad it works for you.
