### ISSUE TITLE
No option 'test_event_server_jane' in section: 'base'

### ISSUE THREAD

**Issue by samuelchodur** [megies/obspyck#71]
Trying to run obspyck for the first time and I receive the following error:

```
$ obspyck --time 2017-12-03T05:11:00 --duration 3600 python/obspy/waveforms/IM.I56* python/obspy/stations/IM.I56*
Running ObsPyck version 0.5.1 (location: /home/kodur/.conda/envs/obspyck/lib/python2.7/site-packages/obspyck/obspyck.pyc)
using config file: /home/kodur/.obspyckrc
================================================================================
Reading local files:
--------------------------------------------------------------------------------
python/obspy/waveforms/IM.I56H1..BDF__20171203T041100Z__20171203T081100Z.mseed: Waveforms
python/obspy/waveforms/IM.I56H2..BDF__20171203T041100Z__20171203T081100Z.mseed: Waveforms
python/obspy/waveforms/IM.I56H3..BDF__20171203T041100Z__20171203T081100Z.mseed: Waveforms
python/obspy/waveforms/IM.I56H4..BDF__20171203T041100Z__20171203T081100Z.mseed: Waveforms
python/obspy/stations/IM.I56H1.xml: Metadata
python/obspy/stations/IM.I56H2.xml: Metadata
python/obspy/stations/IM.I56H3.xml: Metadata
python/obspy/stations/IM.I56H4.xml: Metadata
================================================================================
Fetching waveforms and metadata from servers:
--------------------------------------------------------------------------------
================================================================================
/home/kodur/.conda/envs/obspyck/lib/python2.7/site-packages/obspyck/obspyck.py:230: UserWarning: Cannot find external programs dir, localization methods/functions are deactivated
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/kodur/.conda/envs/obspyck/bin/obspyck", line 11, in <module>
    load_entry_point('obspyck==0.5.1', 'console_scripts', 'obspyck')()
  File "/home/kodur/.conda/envs/obspyck/lib/python2.7/site-packages/obspyck/obspyck.py", line 4666, in main
    obspyck = ObsPyck(clients, streams, options, KEYS, config)
  File "/home/kodur/.conda/envs/obspyck/lib/python2.7/site-packages/obspyck/obspyck.py", line 263, in __init__
    test_event_server_name = config.get("base", "test_event_server_jane")
  File "/home/kodur/.conda/envs/obspyck/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'test_event_server_jane' in section: 'base'
```

**Comment by megies** [comment]
As a workaround.. just put an empty option `test_event_server_jane =` under the `[base]` section in the config.
