### ISSUE TITLE
Can't run Obspyck properly

### ISSUE THREAD

**Issue by aqualad28** [megies/obspyck#81]
Hello there!
I was try to running Obspyck with some of my .mseed and .SAC data, but it returned an error message like this:

```
GLib-GIO-Message: 10:53:30.448: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
/home/newquest/anaconda2/envs/obspyck/lib/python2.7/site-packages/obspyck/obspyck.py:230: UserWarning: Cannot find external programs dir, localization methods/functions are deactivated
  warnings.warn(msg)
Traceback (most recent call last):
  File "/home/newquest/anaconda2/envs/obspyck/bin/obspyck", line 11, in <module>
    load_entry_point('obspyck==0.5.1', 'console_scripts', 'obspyck')()
  File "/home/newquest/anaconda2/envs/obspyck/lib/python2.7/site-packages/obspyck/obspyck.py", line 4666, in main
    obspyck = ObsPyck(clients, streams, options, KEYS, config)
  File "/home/newquest/anaconda2/envs/obspyck/lib/python2.7/site-packages/obspyck/obspyck.py", line 278, in _init_
    raise Exception(err)
Exception: No streams left to work with after removing bad streams.
```

Here I also attach my files that i try to open. Would you like to help me to solve this problem?
[mydata.zip](https://github.com/megies/obspyck/files/2454709/mydata.zip)

Actually, I'm still trying to figure out how to work with Obspyck. Could you give me some sample data and proper command for Obspyck to run properly?

Thank you :)

**Comment by aqualad28** [comment]
Thank you so much, my Obspyck now can run the data. 
I very much appreciate your help.
