### ISSUE TITLE
Integrating Hypo2000, NLLoc and Focmec into Obspyck

### ISSUE THREAD

**Issue by kaboom23** [megies/obspyck#83]
Hi,
I was succesfully install obspyck but i get problem when i try to integrating with hypo2000, NLLoc and focmec. I was change the `pluginpath` in config file into the directory where i put hypo2000, NLLoc and focmec folder. But i still get the following error :

hypo2000
```
Traceback (most recent call last):
  File "/home/kaboom/anaconda2/envs/obspyck/lib/python2.7/site-packages/obspyck/obspyck.py", line 469, in on_qToolButton_doHyp2000_clicked
    self.doHyp2000()
  File "/home/kaboom/anaconda2/envs/obspyck/lib/python2.7/site-packages/obspyck/obspyck.py", line 2118, in doHyp2000
    files = prog_dict['files']
KeyError: 'files'
```
NLLoc
```
Traceback (most recent call last):
  File "/home/kaboom/anaconda2/envs/obspyck/lib/python2.7/site-packages/obspyck/obspyck.py", line 483, in on_qToolButton_doNlloc_clicked
    self.doNLLoc()
  File "/home/kaboom/anaconda2/envs/obspyck/lib/python2.7/site-packages/obspyck/obspyck.py", line 2150, in doNLLoc
    files = prog_dict['files']
KeyError: 'files'
```

focmec
```
Traceback (most recent call last):
  File "/home/kaboom/anaconda2/envs/obspyck/lib/python2.7/site-packages/obspyck/obspyck.py", line 495, in on_qToolButton_doFocMec_clicked
    self.doFocmec()
  File "/home/kaboom/anaconda2/envs/obspyck/lib/python2.7/site-packages/obspyck/obspyck.py", line 1859, in doFocmec
    files = prog_dict['files']
KeyError: 'files'
```
Thanks,

**Comment by megies** [comment]
There's several tickets on these kind of problems, please make sure you read through these first. I know the program integration is far from ideal right now, but I just did never get to cleaning it up properly..
